Fix mef amounts
betagouv/aplypro pull request #261
Opened 2023-12-05 14:35 UTC by JeSuisUnCaillou

2023-12-05 16:07 UTC, JeSuisUnCaillou commented
J'attend encore les MEFs amounts manquants de Christel.

2023-12-05 16:32 UTC, freesteph requested changes

2023-12-05 16:32 UTC, freesteph commented on db/migrate/20231205132222_add_mef_code_to_wages.rb
> +      table.string :mef_code, null: false
foreign key vers la table MEF

2023-12-08 16:50 UTC, freesteph commented on db/wage_mefstat4_seeder.rb
> +class WageMefstat4Seeder
delete

2023-12-08 16:50 UTC, freesteph commented on db/wage_seeder.rb
> +    Wage.delete_all
ce serait mieux de faire de l'upsert je pense

2023-12-08 16:50 UTC, freesteph commented on db/wage_seeder.rb
> +end
je comprends absolument rien, c'est quoi le produit final ?

2023-12-08 16:50 UTC, freesteph commented on spec/models/mef_spec.rb
> +  end
tu peux faire écrire ton test autour du

```ruby
context('when there are multiple wages for the same MEFSTAT4')
```

ce qui est le tournant principal de logique ici

2023-12-08 17:05 UTC, JeSuisUnCaillou commented on db/wage_seeder.rb
> +end
la liste des codes mefs de chaque groupe (mefstat4+ministry+montants) qui apparaît plus d'une fois

2023-12-08 17:10 UTC, JeSuisUnCaillou commented on db/wage_seeder.rb
> +    Wage.delete_all
L'impact de performance est négligeable, et pour update la data existante il faut d'abord identifier ce qui est gardable en terme de "mefstat4+montants", ce qui demande plus de code.

Ca vaut pas le coup.

2023-12-08 17:39 UTC, JeSuisUnCaillou commented on db/wage_seeder.rb
> +end
Je suis d'accord que c'est obscur, mais si tu veux m'aider à prendre du recul faut me dire quelles parties te semblent vraiment imbitable, par ce que ça m'étonnerait que tu ne comprennes absolument rien.

2023-12-11 08:11 UTC, freesteph commented on db/wage_seeder.rb
> +end
je vais regarder de mon côté

2023-12-11 08:15 UTC, freesteph commented on spec/models/mef_spec.rb
> +        wrong_wage
encore une fois, si tu fais des evals dans un before c'est `let!()`

2023-12-11 08:15 UTC, JeSuisUnCaillou commented on db/migrate/20231208091401_add_mef_code_to_wages.rb
> +    WageSeeder.seed
Si on fait la migration sans insérer les données, on va péter l'app.

Pour cette migration-ci, le données de seed doivent être insérées avec la migration sinon plus aucun montant ne peut être récupéré.

2023-12-11 08:26 UTC, freesteph commented on db/wage_seeder.rb
> +end
alors je devine mais je comprends toujours pas bien, est-ce que c'est possible d'en faire moins avec : 

```ruby
    data = CSV.read(Rails.root.join("data/mefs-amounts.csv"), headers: true)

    data
      .group_by { |d| d.fields(*WAGE_MAPPING.values) }
      .uniq
      .compact
```

qui te donne 

```ruby
[
  [["15", "600", "2212", "MENJ"],
  [#<CSV::Row "MEF":"2212421011" "MEF_STAT_11":"22123124210" "MEF_STAT_4":"2212" "DISPOSITIF_FORMATION":"221" "LIBELLE_LONG":"1BT,
 ... tous les mefs],
  [["20", "800", "2213", "MENJ"],
  [array des MEFS correspondants]
]
etc
```
]

2023-12-11 08:26 UTC, JeSuisUnCaillou commented on spec/models/mef_spec.rb
> +        wrong_wage
Mais ça m'ennuie par ce que j'aimais bien avoir un nom de variable `wrong_wage`, ça rendait le truc plus lisible.

2023-12-11 08:28 UTC, freesteph commented on spec/models/mef_spec.rb
> +    context "when there is several wages with mefstat4 & ministry" do
are

2023-12-11 08:35 UTC, JeSuisUnCaillou commented on db/wage_seeder.rb
> +end
Et on insère la liste des mef_codes pour toutes les lignes ? Ouais pourquoi pas. En vrai ça serait une bonne chose, on aurait du coup moyen de faire un join custom sur le mef code comme ça, pour les stats.

2023-12-11 09:35 UTC, freesteph commented on db/wage_seeder.rb
> +    grouped_wages = data.group_by { |d| d.fields(*WAGE_MAPPING.values) }
tu peux éviter la variable et faire du chaining sur une nouvelle ligne?

2023-12-11 09:35 UTC, freesteph commented on features/step_definitions/perdir_steps.rb
> +  @mef = Mef.find_by(code: mef) || FactoryBot.create(:mef, label: mef)
pourquoi on fait un find maintenant?

2023-12-11 09:46 UTC, JeSuisUnCaillou commented on features/step_definitions/perdir_steps.rb
> +  @mef = Mef.find_by(code: mef) || FactoryBot.create(:mef, label: mef)
C'est un reliquat de mon ancienne méthode

2023-12-11 09:49 UTC, freesteph commented on spec/models/mef_spec.rb
> +      it "returns the only wage" do
mauvais intitulé

2023-12-11 09:49 UTC, freesteph commented on features/step_definitions/perdir_steps.rb
> +  @mef = Mef.find_by(code: mef) || FactoryBot.create(:mef, label: mef)
et donc on garde ?

2023-12-11 09:55 UTC, JeSuisUnCaillou commented on features/step_definitions/perdir_steps.rb
> +  @mef = Mef.find_by(code: mef) || FactoryBot.create(:mef, label: mef)
Non j'ai enlevé

2023-12-11 10:53 UTC, JeSuisUnCaillou commented on spec/models/mef_spec.rb
> +      it "returns the only wage" do
bien vu

2023-12-11 12:16 UTC, freesteph commented on spec/models/mef_spec.rb
> +        wage
let!

2023-12-11 12:20 UTC, freesteph approved these changes

2023-12-11 12:44 UTC, merged