auth: Sentry log when establishment tries to update student_provider
betagouv/aplypro pull request #289
Opened 2023-12-12 14:58 UTC by JeSuisUnCaillou

2023-12-13 16:10 UTC, freesteph requested changes
j'aimerais qu'on passe par une erreur plutôt

2023-12-13 16:10 UTC, freesteph commented on app/models/concerns/identity_mappers/base.rb
> +      establishment = Establishment.find_or_create_by!(uai: uai)
```ruby
    class StudentsProviderMismatch < Error
      def initialize(msg = "Tried to change an establishment's student provider")
        super(msg)
      end
    end
```

```ruby
    def find_or_create_establishment!(uai)
      Establishment.find_or_create_by!(uai: uai, students_provider: students_provider)
    rescue ActiveRecord::RecordInvalid
      raise StudentsProviderMismatch, "[#{uai}]: tried to update to #{students_provider}"
    end
```

2023-12-14 08:53 UTC, JeSuisUnCaillou commented on app/models/concerns/identity_mappers/base.rb
> +      establishment = Establishment.find_or_create_by!(uai: uai)
Ca empêchera pas de se connecter de garder une erreur ?

2023-12-14 09:12 UTC, JeSuisUnCaillou commented on app/models/concerns/identity_mappers/base.rb
> +      establishment = Establishment.find_or_create_by!(uai: uai)
Il me semble préférable de laisser les users consulter l'établissement avec le provider que l'établissement a déjà, quelque soit le provider du user actuel.

Et de base le `Establishment.find_or_create_by!(uai: uai, students_provider: students_provider)` ne me semble pas une bonne idée vis à vis du fait qu'on a une contrainte sur l'unicité de l'UAI seulement. Si on veut faire ce `find_or_create_by` avec le provider dedans, il faudrait mettre la contrainte d'unicité sur `UAI`+`provider`, et autoriser un établissement à exister avec chaque provider différent.

Mais ça ferait parti d'une PR plus large sur la gestion des établissements sous double tutelle. En attendant, je veux juste éviter les écrans d'erreurs Rails à la connexion.

2023-12-14 09:17 UTC, JeSuisUnCaillou commented on app/models/concerns/identity_mappers/base.rb
> +      establishment = Establishment.find_or_create_by!(uai: uai)
Ou alors il faut que le message d'erreur à la connexion soit user friendly, pour les remontées au support.

"Connectez-vous avec un compte MENJ pour accéder à l'établissement #{uai}"

2023-12-14 09:24 UTC, JeSuisUnCaillou commented on app/models/concerns/identity_mappers/base.rb
> +      establishment = Establishment.find_or_create_by!(uai: uai)
Ou alors si on veut vraiment être stricts, il faudrait un message plus clair du genre :
```
Connectez-vous avec un compte MENJ pour accéder à l'établissement #{UAI}
```

Mais ça reste embêtant pour les gens qui ont plusieurs établissements sous leur responsabilité, si un de ces étab vient à leur empêcher l'entrée alors que c'est pas celui qu'ils viennent consulter avec leur compte c'est dommage.

2023-12-14 13:34 UTC, JeSuisUnCaillou commented on app/models/concerns/identity_mappers/base.rb
> +      establishment = Establishment.find_or_create_by!(uai: uai)
Et on a le cas d'établissements gérés par des users au comptes MASA qui ont les données d'élèves dans les bases du MENJ : 0881593D et 0761315S.

2023-12-14 14:17 UTC, freesteph approved these changes

2023-12-14 14:17 UTC, merged