Home : current pfmps indicators should not count closed schoolings
betagouv/aplypro pull request #322
Opened 2023-12-21 16:31 UTC by JeSuisUnCaillou

2023-12-22 13:10 UTC, freesteph requested changes

2023-12-22 13:10 UTC, freesteph commented on features/step_definitions/home_steps.rb
> +  within("##{id}") do
idem

2023-12-22 14:32 UTC, JeSuisUnCaillou commented on features/accueil.feature
> +    Alors l'indicateur de pfmp avec l'id "pending_count" affiche 0
aria-label="Nombre de pfmp complétées"

2023-12-27 08:39 UTC, freesteph approved these changes

2023-12-27 08:39 UTC, merged