Closed schoolings management
betagouv/aplypro pull request #413
Opened 2024-01-24 17:02 UTC by JeSuisUnCaillou

2024-01-29 17:47 UTC, JeSuisUnCaillou reviewed
L'implémentation de la gestion des anciens élèves a eu quelques conséquences supplémentaires :

- Gros changement pour les routes de PFMP : elles sont désormais nested sous schooling au lieu de student, pour permettre la gestion de schoolings autre que la current.

- Les DA sont désormais générées à partir d'une schooling, et plus d'un étudiant

- Dans le show d'un étudiant, je n'affiche plus que les schoolings de la classe du breadcrumb. C'est un parti pris, mais ça se discute. 

Y'a aussi quelques optimisations de requêtes de listes (liste des élèves, liste des ribs, liste des pfmps) en faisant les bons includes, et en passant par les bons modèles lors des `enchainements.de.trucs.comme.ça`

Bon courage pour la review, y'a beaucoup de fichiers :muscle:

2024-01-31 14:44 UTC, skelz0r requested changes
Globalement les controllers sont trop gros, faudrait se forcer à n'instancier que les modèles principaux du controller (namespace et le model du nom du controller) et des façades pour cacher les complexités et ainsi testé en isolation tous les traitements lourds.

Mise à part ce refacto (que je juge nécessaire pour vraiment simplifier les controllers qui se trimballent déjà des breadcrumbs partout), cela me semble logique dans l'ensemble.

2024-01-31 14:44 UTC, skelz0r commented on features/anciens_eleves.feature
> +  Scénario: Les anciens élèves sont affichés dans le compteur des saisies banciares
```suggestion
  Scénario: Les anciens élèves sont affichés dans le compteur des saisies bancaires
```

typo

2024-01-31 17:19 UTC, JeSuisUnCaillou commented on app/controllers/classes_controller.rb
>    end
J'ai fait la facade.
Mais pas convaincu qu'il y ait besoin de tester unitairement chaque requête de la facade.
Les tests e2e les couvrent bien selon moi.

2024-01-31 17:22 UTC, skelz0r commented on app/controllers/classes_controller.rb
>    end
C'est en effet simple, le "permettra" était au future si il y a des requêtes plus complexes (ou à optimiser)

2024-01-31 17:47 UTC, JeSuisUnCaillou commented on app/jobs/fetch_student_information_job.rb
> +    student = schooling.student
Par ce que pour savoir dans l'API de quel ministère (MENJ ou MASA) aller chercher les data d'un étudiant, il faut connaître son établissement.

Je veux arrrêter de me baser sur `student.current_schooling` pour trouver l'établissement, sinon on peut avoir des infos d'étudiant provenant du MASA dans un établissement MENJ, ce qui peut être confusant pour les utilisateurs.

Il faut que les informations d'étudiant reflètent celles de leur SI habituel de leur ministère, sinon ils auront pas la main dessus.

Peut-être passer un étudiant + établissement en paramètre au lieu d'une scolarité alors ?

2024-01-31 17:50 UTC, skelz0r commented on app/jobs/fetch_student_information_job.rb
> +    student = schooling.student
Non ça me semble OK comme justification.

2024-02-01 08:47 UTC, JeSuisUnCaillou commented on app/controllers/home_controller.rb
>    end
Ah oui :)

2024-02-01 08:55 UTC, JeSuisUnCaillou commented on app/controllers/ribs_controller.rb
>      if @ribs.each(&:save).all?(&:valid?)
Comment ça, ça va le mettre à genoux ? On sauvegarde une 30aine de lignes à la fois grand max (une classe quoi)

Pour explication, ici on fait `each(&:save)` d'abord pour tous tenter de les save sans s'arrêter au premier échec, puis `all?(&:valid?)` pour vérifier si il y a des échecs.

L'idée étant de n'afficher que les ribs échoués sur le render en cas d'erreur, ne ayant validé tous les autres. 
Mais ! Je me rend compte que ça lève une erreur 403 là je vais voir pour fix ça.

2024-02-01 08:56 UTC, JeSuisUnCaillou commented on app/controllers/ribs_controller.rb
>      if @ribs.each(&:save).all?(&:valid?)
Mais intéressant le bulk insert là, je me suis souvent dit que c'était relou de pas pouvoir faire ça.

2024-02-01 09:03 UTC, skelz0r commented on app/controllers/ribs_controller.rb
>      if @ribs.each(&:save).all?(&:valid?)
J'exagère un peu, mais on se retrouve avec N requêtes SQL atomique vs une transaction, je pense que ça serait mieux de généraliser via un service qui wrap un truc comme cette gem et gère les bulk erreurs.

2024-02-01 09:04 UTC, JeSuisUnCaillou commented on app/controllers/ribs_controller.rb
>      if @ribs.each(&:save).all?(&:valid?)
AH, alors on a un problème avec le `check_classes` qui vérifie qu'on essaye pas d'envoyer des ribs pour des étudiants qu'on n'a pas à gérer : Comme dans ma data j'ai des étudiants avec plusieurs classes, mon check n'est plus bon.

-> https://github.com/betagouv/aplypro/blob/closed_schoolings_management/app/controllers/ribs_controller.rb/#L127-L140

Il faut que je vérifie que chaque est étudiant est _au moins_ dans la classe courante. Là je vérifie que mes étudiants sont _uniquement_ dans ma classe courante, ça va pas. Je vais ajouter un test.

2024-02-01 09:09 UTC, skelz0r commented on app/controllers/ribs_controller.rb
>      if @ribs.each(&:save).all?(&:valid?)
Typiquement quand c'est aussi complexe je wrapperai ça dans un service pour bien tester en isolation les cas --^
J'en ferai même un ActiveModel pour bundler les erreurs ensemble, faire un form avec l'objet etc etc

2024-02-01 09:23 UTC, JeSuisUnCaillou commented on app/controllers/ribs_controller.rb
>      if @ribs.each(&:save).all?(&:valid?)
J'ai réglé ça. C'est un problème qui peut déjà arriver en prod en plus je pense, étrange qu'on l'ait pas encore vu passer.

2024-02-01 09:24 UTC, JeSuisUnCaillou commented on app/controllers/ribs_controller.rb
> +      set_closed_schoolings
ça part en facade :D

2024-02-01 09:25 UTC, freesteph reviewed
première passe, je relis

2024-02-01 09:25 UTC, freesteph commented on app/models/classe.rb
> +    schoolings.find_by(student: student)
est-ce qu'on peut remettre ça inline ?

2024-02-01 09:25 UTC, freesteph commented on spec/factories/classes.rb
> +        classe.reload
pourquoi le reload?

2024-02-01 09:25 UTC, freesteph commented on spec/jobs/generate_missing_attributive_decisions_job_spec.rb
> +      expect { job.perform_now }.to have_enqueued_job.with(schooling)
?

2024-02-01 09:25 UTC, freesteph commented on app/controllers/ribs_controller.rb
> +      set_closed_schoolings
oui pourquoi faire ça ici ?

2024-02-01 09:33 UTC, JeSuisUnCaillou commented on app/controllers/validations_controller.rb
> +    @classes_facade = ClassesFacade.new(@classes)
oui ça devrait

2024-02-01 09:36 UTC, JeSuisUnCaillou commented on app/controllers/validations_controller.rb
> +    @classes_facade = ClassesFacade.new(@classes)
Non en fait il faut pluôt virer la variable et mieux faire @classes là

2024-02-01 09:43 UTC, JeSuisUnCaillou commented on app/controllers/validations_controller.rb
>    def validation_params
J'ai pas tout compris. Mais j'ai vu "rien à voir avec cette PR" donc on peut en reparler plus tard j'imagine ;)

2024-02-01 09:46 UTC, skelz0r commented on app/controllers/validations_controller.rb
>    def validation_params
`params.require` lève une erreur si la clé est absente. C'est voulu dans la philosophie de StrongParameter, et ça permet de faire un catch global dans le controller de base (et ainsi renvoyer une erreur de type 400 car c'est théoriquement impossible quand on soumet un form basé sur un model de ne pas avoir cette clé).

2024-02-01 09:50 UTC, JeSuisUnCaillou commented on spec/factories/classes.rb
> +        classe.reload
Pour la même raison qu'il y a 4 mois quand on a fait la même chose juste au dessus, ligne 19 : Si on reload pas l'instance sort de la factory avec une liste de schoolings pas à jour.

Mais après avoir relancé les tests sans, je vois que ça passe, c'est possible qu'on ait changé la manière dont on utilise ces factories entre temps. Donc je vais les retirer.

2024-02-01 09:52 UTC, JeSuisUnCaillou commented on app/models/classe.rb
> +    schoolings.find_by(student: student)
C'est à dire, c'est pas inline là ?

2024-02-01 09:54 UTC, JeSuisUnCaillou commented on app/helpers/classes_helper.rb
> +    return if schooling.blank? || schooling.open?
Quand j'utilise cette méthode dans `ribs/missing`

2024-02-01 09:56 UTC, JeSuisUnCaillou commented on app/views/classes/_students_table.html.haml
> +- caption ||= ""
C'est plus un moyen d'informer le dévellopeur que ce sont les variables nécessaires à cette vue. J'y tiens pas tant que ça, je les retire.

2024-02-01 09:56 UTC, skelz0r commented on app/helpers/classes_helper.rb
> +    return if schooling.blank? || schooling.open?
(je trouve ça mieux de faire cette condition ici que dans la vue vu que c'est informatif, cette méthode encapsule lui même sa logique d'affichage)

2024-02-01 09:57 UTC, JeSuisUnCaillou commented on spec/jobs/generate_missing_attributive_decisions_job_spec.rb
> +      expect { job.perform_now }.to have_enqueued_job.with(schooling)
Quelle est la question ? 

On a déjà parlé de ce genre de chose, je ne peut pas lire dans les pensées. Il faut me dire ce qui ne va pas pour que je puisse répondre ou corriger.

2024-02-01 09:59 UTC, skelz0r commented on spec/jobs/generate_missing_attributive_decisions_job_spec.rb
> +      expect { job.perform_now }.to have_enqueued_job.with(schooling)
L'intitulé du test ne correspond pas au test effectif

2024-02-01 10:56 UTC, JeSuisUnCaillou commented on app/controllers/ribs_controller.rb
>      if @ribs.each(&:save).all?(&:valid?)
Ah tiens, je voyais pas tes messages quand j'écrivais tout ça.

Du coup j'ai simplifié le check, mais je vais pas me lancer dans le bulk insert dans cette PR.

2024-02-01 10:59 UTC, JeSuisUnCaillou commented on app/controllers/validations_controller.rb
>    def validation_params
Ah ok ! En fait avec `check_empty_params` je voulais juste m'assurer que le user avait pas décoché toutes les PFMPs avant de cliquer sur valider. Et je me suis rendu compte que si il décochait tout, le form enlevait la clef `params[:validation]` qui était required.

Tu conseille de mettre un catch dans `validation_params` à la place du coup c'est ça ?

2024-02-01 11:01 UTC, JeSuisUnCaillou commented on spec/jobs/generate_missing_attributive_decisions_job_spec.rb
> +      expect { job.perform_now }.to have_enqueued_job.with(schooling)
Ah oui ça effectivement.

2024-02-01 11:06 UTC, JeSuisUnCaillou commented on app/controllers/ribs_controller.rb
>      if @ribs.each(&:save).all?(&:valid?)
> Typiquement quand c'est aussi complexe je wrapperai ça dans un service pour bien tester en isolation les cas --^
> J'en ferai même un ActiveModel pour bundler les erreurs ensemble, faire un form avec l'objet etc etc

C'est plus aussi complexe maintenant je trouve : 

```ruby
students_not_in_class = bulk_ribs_params.pluck(:student_id).map(&:to_i) - @classe.students.pluck(:id)

if students_not_in_class.present?
    gtfo()
```

Ca mérite toujours un service selon toi ?

2024-02-01 11:43 UTC, skelz0r commented on app/controllers/ribs_controller.rb
>      if @ribs.each(&:save).all?(&:valid?)
De manière général ça + le fait que tu doives faire un traitement spécial des paramètres fait que c'est moins rails way. Si c'était isolé ça serait ~ok, mais ici vous manipulez 2 bulks dans 2 controllers, normaliser ça avec un seul model qui encapsule la logique dans du ActiveModel ferait que ça serait plus rails way, plus facile à tester (surtout si on veut des comportements plus fin à tester) et rendrait les controller plus skinny.

En bref, c'est plus propre. 

Après ça peut se faire en dehors de cette PR (imo c'est mieux), tu déportes dans un ticket.

2024-02-01 14:35 UTC, JeSuisUnCaillou commented on app/controllers/validations_controller.rb
>    def validation_params
Je vais faire la version kiss alors, par ce que sinon je dois me lancer aussi dans la création des pages d'erreurs (qu'on a pas aujourd'hui, les gens se mangent la page d'erreur scalingo)

2024-02-01 14:40 UTC, skelz0r commented on app/controllers/validations_controller.rb
>    def validation_params
Oui c'est le mieux dans le cadre de cette PR

2024-02-01 14:51 UTC, JeSuisUnCaillou commented on app/controllers/ribs_controller.rb
>      if @ribs.each(&:save).all?(&:valid?)
Issue https://github.com/betagouv/aplypro/issues/437

2024-02-01 15:06 UTC, merged