rib: remove more offending characters
betagouv/aplypro pull request #715
Opened 2024-04-12 06:04 UTC by freesteph

Closes #712.

2024-04-12 13:56 UTC, JeSuisUnCaillou requested changes

2024-04-12 13:56 UTC, JeSuisUnCaillou commented on app/models/rib.rb
> +  normalizes :name, with: ->(name) { name.squish.gsub(";", " ") }
il faut aussi enlever `¨`

2024-04-12 14:27 UTC, freesteph commented on app/models/rib.rb
> +  normalizes :name, with: ->(name) { name.squish.gsub(";", " ") }
https://github.com/betagouv/aplypro/pull/715/commits/ef414856dbae4a8c9562a33681a055fdd714512f

2024-04-12 14:28 UTC, freesteph commented on app/models/rib.rb
> +  normalizes :name, with: ->(name) { name.squish.gsub(";", " ") }
en TL&DR: [on enlève déjà tous les accents dans le `ASP::Builder`](https://github.com/betagouv/aplypro/blob/main/lib/asp/builder.rb#L18) et ça nous permet de garder les vrais noms (genre "Stéphane" et pas "Stephane" comme si on était une boîte des années 90)

2024-04-15 08:18 UTC, JeSuisUnCaillou approved these changes

2024-04-15 08:27 UTC, merged