Stats of payments
betagouv/aplypro pull request #766
Opened 2024-04-22 11:57 UTC by JeSuisUnCaillou

2024-05-07 16:37 UTC, JeSuisUnCaillou commented on spec/factories/asp/payment_requests.rb
> +        req.reload ## needed to reload the data of the schooling for the asp xml builder
Je pense qu'il y a moyen de faire mieux que ça, mais j'suis déjà tellement content que ça fonctionne comme je veux que j'ai pas été plus loin. Je prend toute suggestion d'amélioration avec plaisir.

2024-05-13 08:47 UTC, pskl requested changes
Beau boulot!

Cependant pour moi l'aspect sécu du script est bloquant.

Le reste des mes remarques sont cosmétiques principalement.

2024-05-13 08:47 UTC, pskl commented on app/models/stats/main.rb
> +        end.join("\t")
C'est quoi "\t" ? Je connais pas

2024-05-13 08:47 UTC, pskl commented on script/stats/execute_in_prod.sh
> +scalingo -region osc-secnum-fr1 --app $production_name run rails runner \""$escaped_ruby_string"\" | sed "1d" > $output_file_path
On ne devrait pas exposer l'instance de prod dans le repo tant qu'il est public, tu peux soit garder ce script en local chez toi soit interpoler une variable d'environnement avec la donnée sensible.

D'ailleurs ca pourrait être un script ruby cette affaire avec un call system en utilisant:  ``truc`` (mais pas bloquant) pour éviter de faire des `sed` et des `echo`?

2024-05-13 08:47 UTC, pskl commented on spec/factories/asp/payment_requests.rb
> +        req.student.update!(**student.attributes.except("id", "updated_at", "created_at"))
Oui ca commence à être la boucherie là dedans mais de mon point de vue c'est pas bloquant car c'est souvent le cas avec FactoryBot et pour moi si la suite de test dit oui je dis oui.

2024-05-13 08:47 UTC, pskl commented on spec/models/stats/indicator/payment_request_states_spec.rb
> +describe Stats::Indicator::PaymentRequestStates do
Propre !

2024-05-13 08:47 UTC, pskl commented on spec/support/attributive_decision_helpers.rb
> +    schooling.rattach_attributive_decision!(StringIO.new("hello"))
Peut-être un truc plus "proche" de la vraie donnée que "hello" ici?

2024-05-13 09:53 UTC, JeSuisUnCaillou commented on app/models/stats/main.rb
> +        end.join("\t")
c'est une tabulation. Ca permet de coller les cellules de manière très directe dans le tableur

2024-05-13 09:53 UTC, JeSuisUnCaillou commented on script/stats/execute_in_prod.sh
> +scalingo -region osc-secnum-fr1 --app $production_name run rails runner \""$escaped_ruby_string"\" | sed "1d" > $output_file_path
J'ai pas mis le nom de l'instance de prod, j'ai mis une variable `production_name` justement là

2024-05-13 09:54 UTC, JeSuisUnCaillou commented on script/stats/execute_in_prod.sh
> +scalingo -region osc-secnum-fr1 --app $production_name run rails runner \""$escaped_ruby_string"\" | sed "1d" > $output_file_path
Pour le faire ne ruby, j'ai pas trouvé plus direct. Y'a bien un moment où faut envoyer le ruby dans la commande bash scalingo, et c'est ce que je fait là.

2024-05-13 09:56 UTC, JeSuisUnCaillou commented on spec/support/attributive_decision_helpers.rb
> +    schooling.rattach_attributive_decision!(StringIO.new("hello"))
J'ai juste repris la méthode que j'ai factorisé qui faisait déjà ça avec "hello".

On n'inspecte jamais le contenu du pdf en fait, donc peu improte selon moi.

2024-05-13 09:59 UTC, pskl commented on app/models/stats/main.rb
> +        end.join("\t")
Ok

2024-05-13 10:02 UTC, pskl commented on script/stats/execute_in_prod.sh
> +scalingo -region osc-secnum-fr1 --app $production_name run rails runner \""$escaped_ruby_string"\" | sed "1d" > $output_file_path
Je pense que ca serait bien d'occulter la region aussi? C'est une info de targeting potentiellement utilisable. Mais ok je débloque si le nom de l'app est déjà occulté ca me va.

Le Ruby ca t'éviterait juste les lignes du dessus avec sed/etc, effectivement derrière y'a un call system avec interpolation et paramètres.

2024-05-13 10:02 UTC, pskl commented on spec/support/attributive_decision_helpers.rb
> +    schooling.rattach_attributive_decision!(StringIO.new("hello"))
Vendu!

2024-05-13 10:03 UTC, pskl approved these changes

2024-05-13 10:05 UTC, merged