#721 nettoyage des locales
betagouv/aplypro pull request #808
Opened 2024-04-26 15:25 UTC by ac-clermont-dylan

2024-04-29 12:04 UTC, pskl commented on config/locales/fr.yml
> -              less_than_or_equal_to: "n'est pas cohérent avec les dates de début et de fin"
Ton CI il pète parce-que typiquement cette locale là est utilisée dans la validation sur le modèle Pfmp donc elle est à garder, pareil pour les autres erreurs je suppose! La structure du fichier te donne un indice sur l'utilité de la traduction. En l'occurence celle-ci sert à traduire les erreurs d'attributs durant la validation.

2024-05-02 08:02 UTC, freesteph requested changes

2024-05-02 08:02 UTC, freesteph commented on config/locales/fr.yml
> -        name: "Nom"
ça aussi, tout ce qui tombe dans le namespace `activerecord` il faut faire attention parce que c'est inféré de manière automatique.

2024-05-02 08:02 UTC, freesteph commented on config/locales/fr.yml
> -        select_establishment: Choix de l'établissement
aussi utilisé

2024-05-02 08:02 UTC, freesteph commented on config/locales/fr.yml
> -        bulk_create: *missing_ribs_title
aussi utilisé je pense

2024-05-02 09:14 UTC, freesteph commented on config/locales/fr.yml
> -        update: *edit_rib_title
tout ça sont des titres de pages, tu t'es assuré que le titre de la page était toujours bon ?

2024-05-06 07:54 UTC, freesteph reviewed
Just le coup de la version de Bundler et après c'est bon 🐎

2024-05-06 07:54 UTC, freesteph commented on Gemfile.lock
> -   2.5.9
pourquoi as-tu enlevé ça ?

2024-05-06 08:07 UTC, ac-clermont-dylan commented on Gemfile.lock
> -   2.5.9
C'est un résidu de ce qu'on avait fait avec Thibault quand on avait nos problèmes d'environnement, ça n'aurait pas du être commité en effet.

2024-05-06 08:24 UTC, pskl approved these changes

2024-05-06 08:30 UTC, freesteph approved these changes

2024-05-06 08:31 UTC, merged