List incomplete payment requests reasons
betagouv/aplypro pull request #832
Opened 2024-05-02 15:19 UTC by pskl

Closes #748 

- [x] Fix facade query bug in a better way
- [x] Display <ul> list of reasons in case of many reasons
- [ ] Make the decorator code a bit better

2024-05-02 15:35 UTC, pskl commented on app/decorators/asp/payment_request_decorator.rb
> +      { reason_method.name => reason_method.call }
c'est un draft fréro

2024-05-02 16:03 UTC, freesteph commented on app/decorators/asp/payment_request_decorator.rb
> +      { reason_method.name => reason_method.call }
d'accord

2024-05-07 09:14 UTC, freesteph commented on app/models/asp/payment_request_validator.rb
> +      add_error(:doesnt_live_in_france) unless student.lives_in_france?
lives_abroad

2024-05-07 09:14 UTC, freesteph commented on app/services/pfmp_manager.rb
> +    !last_payment_request.reload.in_state?(:incomplete)
?

2024-05-07 09:14 UTC, freesteph commented on config/locales/fr.yml
> +        success: Le paiement a été relancé avec succès pour %{name}
demande de

2024-05-07 09:14 UTC, freesteph commented on spec/requests/payment_requests_controller_spec.rb
> +      allow(pfmp_manager).to receive(:retry_incomplete_payment_request!)
nice

2024-05-07 09:14 UTC, freesteph commented on spec/services/pfmp_manager_spec.rb
> +        payment_request.student.update!(address_country_code: "99100")
comment tu sais que c'est ça ?

2024-05-07 09:14 UTC, freesteph commented on app/decorators/asp/payment_request_decorator.rb
> +      if args.is_a?(Array)
quand est-ce que c'est pas un array?

2024-05-07 09:14 UTC, freesteph commented on app/decorators/asp/payment_request_decorator.rb
> +      { reason_method.name => reason_method.call }
la version de gauche reste largement plus claire

2024-05-07 09:14 UTC, freesteph commented on app/facades/validations_facade.rb
> +        .select { |pfmp| pfmp.payment_requests.last.failed? }
c'est pas déjà dans le scope de failed au dessus ?

2024-05-07 09:32 UTC, JeSuisUnCaillou requested changes
je propose une harmonisation des raisons d'échec sous le nommage `failure_reasons` pour simplifier pas mal de code.

2024-05-07 09:32 UTC, JeSuisUnCaillou commented on app/decorators/asp/payment_request_decorator.rb
> +    end
`rejection_reason`, `unpaid_reason` et `incomplete_reason` je les verrait bien dans le modèle par ce que moi j'aimerais bien les utiliser en console sans avoir à déclarer un décorator.

2024-05-07 09:32 UTC, JeSuisUnCaillou commented on app/decorators/asp/payment_request_decorator.rb
> +    end
Je pense qu'on gagnerait en simplicité si on avait une méthode `failure_reasons` telle que : 

```ruby
def failure_reasons
  if in_state?(:incomplete)
    incomplete_reason
  elsif in_state?(:rejected)
    rejection_reason
  elsif in_state?(:unpaid)
    unpaid_reason
  else
    nil
  end
end
```

2024-05-07 09:32 UTC, JeSuisUnCaillou commented on app/decorators/asp/payment_request_decorator.rb
> +        **{ status_explanation_args.keys.first => reason }).html_safe
C'est compliqué à lire, pourquoi on peut pas juste avoir dans `fr.yaml`:
```yaml
incomplete: "Il manque des données pour envoyer le paiement : %{failure_reasons}"
rejected: "La demande a été rejetée : %{failure_reasons}."
unpaid: "Le paiement a été refusé par l'agence comptable : %{failure_reasons}."
```

Et avec la méthode `failure_reasons` que j'ai suggéré plus bas dans le fichier :

```ruby
def status_explanation
  reason = prepare_reason(failure_reasons)
  t("payment_requests.state_explanations.#{current_state}", failure_reasons: reason).html_safe
end
```

2024-05-07 09:32 UTC, JeSuisUnCaillou commented on app/controllers/validations_controller.rb
> -    infer_page_title
Je garderait le page title qui correspond au menu (Paiemnts) et je modifierait le titre de la première table pour qu'il soit un h2 qui correspond à la table : "Pfmps à valider pour envoi en paiement"

2024-05-07 09:32 UTC, JeSuisUnCaillou commented on app/services/pfmp_manager.rb
> +    !last_payment_request.reload.in_state?(:incomplete)
Fait un effort pour préciser ce que tu veux ou demande dans tes commantaires pour permettre une communication rapide stp @freesteph

2024-05-07 09:32 UTC, JeSuisUnCaillou commented on config/locales/fr.yml
> +        failure: La demande de paiement est toujours incomplète pour %{name}, veuillez vous référer à la liste des informations manquantes ci-dessous
J'ajouterai direct la liste des erreurs aussi dans le flash, qui est tout de suite visible au lieu de donner l'instruction de scroller.

2024-05-07 09:32 UTC, JeSuisUnCaillou commented on config/locales/fr.yml
> +              doesnt_live_in_france: "Pour les élèves résidant à l'étranger, des développements sont encore nécessaires avant de pour voir être envoyés à l'Agence de Services et Paiements (ASP). Veui
bien vu :+1: (tu peux resolve ce comm)

2024-05-07 09:32 UTC, JeSuisUnCaillou commented on config/locales/fr.yml
> +        cta: "Débloquer la demande de paiement"
Je propose "Retenter l'envoi en paiement"

2024-05-07 09:32 UTC, JeSuisUnCaillou commented on spec/services/pfmp_manager_spec.rb
> +        payment_request.student.update!(address_country_code: "99100")
Je pense que Stéphane demande de préciser explicitement le contexte du test pour qu'on comprenne mieux pourquoi c'est juste ce code qui manque

2024-05-07 09:34 UTC, JeSuisUnCaillou commented on app/facades/validations_facade.rb
> +        .select { |pfmp| pfmp.payment_requests.last.failed? }
Je pense que c'est ce à quoi il faisait référence ce matin (ou hier matin je sais plus) quand il disait qu'il manquait un filtre dans cette requête.

On voyait encore les payment request échouées dans la liste des échecs même si la pfmp a déjà eu une autre payment request de recréée

2024-05-07 09:36 UTC, JeSuisUnCaillou commented on app/decorators/asp/payment_request_decorator.rb
> +    end
D'ailleurs si on renomme `rejection_reason` en `rejected_reason` ça se fait encore plus vite avec un peu de metaprog

2024-05-07 09:37 UTC, JeSuisUnCaillou commented on config/locales/fr.yml
> +        success: Le paiement a été relancé avec succès pour %{name}
`La demande de paiement a été relancée avec succès pour %{name}`
(au féminin aussi)

2024-05-07 12:38 UTC, freesteph commented on app/services/pfmp_manager.rb
> +    !last_payment_request.reload.in_state?(:incomplete)
OK. Pourquoi il y a cette ligne ? Elle sert à quoi ?

2024-05-07 12:38 UTC, freesteph commented on spec/services/pfmp_manager_spec.rb
> +        payment_request.student.update!(address_country_code: "99100")
merci Sherlock

2024-05-07 12:44 UTC, freesteph commented on app/services/pfmp_manager.rb
> +    !last_payment_request.reload.in_state?(:incomplete)
ça y est j'ai lu le test en bas. C'est obligé le `.reload`? Ça peut être code smell quand c'est du code de prod et pas de test

2024-05-07 13:07 UTC, JeSuisUnCaillou commented on app/facades/validations_facade.rb
> +        .select { |pfmp| pfmp.payment_requests.last.failed? }
Après c'est vrai qu'on se demande à quoi sert le `.merge(ASP::PaymentRequest.latest_per_pfmp.failed)` du coup :thinking: 

C'est pas impossible qu'il penne la "dernière pr failed par pfmp" au lieu de "les failed parmi les dernières pr de pfmps"
J'avais eu ce doute là lors de la PR qui a introduit ces deux scopes, je pense que ça mériterait d'ajouter un test qui vérifie que ces deux scopes ensemble font bien ce à quoi on s'attend.

2024-05-10 09:50 UTC, pskl commented on app/models/asp/payment_request_validator.rb
> +      add_error(:doesnt_live_in_france) unless student.lives_in_france?
On est plutôt sur de la négation dans le nom des clés d'erreurs non?

2024-05-10 09:59 UTC, pskl commented on app/services/pfmp_manager.rb
> +    !last_payment_request.reload.in_state?(:incomplete)
Bien vu! Je rajoute un commentaire et effectivement le reload est pas nécessaire <3

2024-05-10 11:07 UTC, pskl commented on app/decorators/asp/payment_request_decorator.rb
> +      if args.is_a?(Array)
Dans tous les autres cas autre que incomplete c'est pas un array.

2024-05-10 11:25 UTC, pskl commented on app/decorators/asp/payment_request_decorator.rb
> +    end
Bien vu le coup du renommage!

2024-05-10 11:33 UTC, pskl commented on app/decorators/asp/payment_request_decorator.rb
> +      { reason_method.name => reason_method.call }
Implementation remplacée par `failure_reasons`, encore plus clair !

2024-05-10 11:53 UTC, pskl commented on app/controllers/validations_controller.rb
> -    infer_page_title
Done!

2024-05-10 11:58 UTC, pskl commented on config/locales/fr.yml
> +        failure: La demande de paiement est toujours incomplète pour %{name}, veuillez vous référer à la liste des informations manquantes ci-dessous
Je trouve que ca fait redondant et ca nous fait des flash avec des <ul> dedans ce qui demande un peu de hacking comme pour le tableau. Je propose d'explorer le sujet plus tard car je ne suis pas entièrement ok avec cette idée d'injecter du <ul> partout. Il y a un élément d'interface à repenser mais cette PR commence déjà à s'encrouter donc je propose de passer mais je note ton idée quand même?

2024-05-10 12:03 UTC, pskl commented on app/decorators/asp/payment_request_decorator.rb
> +        **{ status_explanation_args.keys.first => reason }).html_safe
Pour l'instant je préfère rester sur un mapping 1:1 avec les accesseurs vu qu'ils sont définis, ca fait moins magique je trouve mais très belle idée !

2024-05-10 13:12 UTC, pskl commented on app/facades/validations_facade.rb
> +        .select { |pfmp| pfmp.payment_requests.last.failed? }
Hop, ca marche en faisant explicitement un INNER JOIN plutôt qu'un merge, je trouve ça même plus lisible.

2024-05-13 07:53 UTC, JeSuisUnCaillou commented on app/decorators/asp/payment_request_decorator.rb
> +        **{ status_explanation_args.keys.first => reason }).html_safe
La méthode est un peu overcomplexe pour moi, mais soit. Avançons.

2024-05-13 07:55 UTC, JeSuisUnCaillou commented on app/decorators/asp/payment_request_decorator.rb
> +    end
Oui, c'est moins pratique, c'est tout.

2024-05-13 07:56 UTC, JeSuisUnCaillou approved these changes
Allez.

2024-05-13 08:05 UTC, freesteph commented on app/models/asp/payment_request_validator.rb
> +      add_error(:doesnt_live_in_france) unless student.lives_in_france?
c'était pour rester cohérent avec ce qu'on a déjà

2024-05-13 08:06 UTC, freesteph commented on app/services/pfmp_manager.rb
> +    !last_payment_request.in_state?(:incomplete)
c'est pas plus logique de regarder si la PR est bien `ready`?

2024-05-13 08:20 UTC, pskl commented on app/decorators/asp/payment_request_decorator.rb
> +        **{ status_explanation_args.keys.first => reason }).html_safe
Oui je te le concède.

2024-05-13 08:20 UTC, pskl commented on app/decorators/asp/payment_request_decorator.rb
> +    end
Oui, c'est vrai

2024-05-13 08:23 UTC, merged

2024-05-13 08:34 UTC, pskl commented on app/services/pfmp_manager.rb
> +    !last_payment_request.in_state?(:incomplete)
Si c'est pas bête, mais pas bloquant, et l'idée c'était de vérifier surtout qu'on sorte de la boucle de incomplet -> incomplete et de déléguer la responsabilité de la transition vers un nouvel état à la SM.

2024-05-13 08:35 UTC, pskl commented on app/models/asp/payment_request_validator.rb
> +      add_error(:doesnt_live_in_france) unless student.lives_in_france?
J'ai justement fait ce changement pour être iso avec le reste des clés d'erreurs !