School year range exceptions
betagouv/aplypro pull request #931
Opened 2024-05-28 11:04 UTC by pskl

Closes #805

2024-05-28 11:08 UTC, pskl commented on spec/rails_helper.rb
> +    Rails.application.load_seed unless database_seeded?
@freesteph Tu peux commenter "ca claque" stp?

2024-05-28 11:11 UTC, pskl commented on app/models/pfmp.rb
> -  scope :this_year, -> { where(start_date: Aplypro::SCHOOL_YEAR_RANGE, end_date: Aplypro::SCHOOL_YEAR_RANGE) }
A ma connaissance:
1) Faux par définition car start_date ne prend pas une Range
2) Pas utilisé dans le code

2024-05-28 12:19 UTC, freesteph commented on spec/rails_helper.rb
> -def check_missing_seed_data!
pourquoi ?

2024-05-28 12:19 UTC, freesteph commented on spec/rails_helper.rb
> +    Rails.application.load_seed unless database_seeded?
damn ça claque

2024-05-28 12:22 UTC, freesteph commented on spec/rails_helper.rb
> +    Mef.count.zero?
`Mef.exists?` ou `Mef.any?`

2024-05-28 12:25 UTC, freesteph commented on app/models/pfmp.rb
> +    "28" => Date.new(Aplypro::SCHOOL_YEAR, 8, 16)  # La Réunion
ça c'est des data sur `Establishment`

2024-05-28 12:25 UTC, freesteph requested changes
C'est cool faut juste bouger les méthodes sur Establishment et après c'est bon. Et si y'a moyen de changer `DEFAULT` en `METROPOLITAN` (puisque l'opposition aux DOM c'est la métropole) mais pas crucial

2024-05-28 12:25 UTC, freesteph commented on app/models/pfmp.rb
> +    start_date = SCHOOL_YEAR_RANGE_EXCEPTIONS.fetch(establishment.academy_code, Aplypro::DEFAULT_SCHOOL_YEAR_START)
pareil sur establishment

2024-05-28 12:27 UTC, freesteph commented on spec/rails_helper.rb
> +    Rails.application.load_seed unless database_seeded?
1% de pref pour la version négative qui encode plus directement le fait que 0 mefs = pas d'appli 

```rb
Rails.application.load_seed if missing_seeds?

def missing_seeds?
  Mef.none?
end
```

2024-05-28 13:10 UTC, pskl commented on spec/rails_helper.rb
> -def check_missing_seed_data!
remplacé par le code plus haut

2024-05-28 13:46 UTC, freesteph commented on app/models/establishment.rb
> +  SCHOOL_YEAR_RANGE_EXCEPTIONS = {
ce sont des `start_date` donc je dirais plutôt 

```rb
SCHOOL_YEAR_SPECIAL_STARTS
```

ou un truc de ton choix mais qui n'encode que le début (après le range c'est +12 mois pour tout le monde)

2024-05-28 13:46 UTC, freesteph commented on config/initializers/year.rb
> +  DEFAULT_SCHOOL_YEAR_RANGE = (DEFAULT_SCHOOL_YEAR_START...DEFAULT_SCHOOL_YEAR_START >> 12)
du coup on peut supprimer ça et utiliser la méthode dans Establishment non?

2024-05-28 13:46 UTC, freesteph commented on spec/models/establishment_spec.rb
> +    context "when the establishment has a default academy_code" do
j'aime pas trop ce terme de "default", c'aurait été plus inclusif avec "metropolitan"

2024-05-29 08:42 UTC, freesteph approved these changes

2024-05-29 08:54 UTC, merged